paths:
  ALL_GH: "../data/elgh/gh_parts/processed_gh_data/filtered_csqs.pkl"
  MIVA_PATH: "../data/elgh/all_functional.gatk_PASS.FS_30.DP_0.GQ_20.AB_0.01.functional.missingness_lt_0.genotype_counts.present_in_ELGH.n_transcripts_corrected.txt"
  GENOME_PATH: "../data/hg38.fasta"
  VP_INFERENCE_PATH: "../models/VariPred/VariPred/predict.sh"
  VP_TRAINING_PATH: "../models/VariPred/VariPred/train_VariPred.sh"
  VP_OUTPUT_PATH: "../data/VariPred/finetuned_output_1/"
  AF_PATH: "../data/alphafold/alphafold_cifs/"
  COMMON_ESSENTIALS_PATH: "../data/depmap/CRISPRInferredCommonEssentials.csv" # 23Q2 release
  GENE_DRUG_EVIDENCE_PATH: "../data/pharmgkb/clinicalAnnotations/clinical_annotations.tsv"
  PROTEIN_ATLAS_FEATURES: "../data/hpa/proteinatlas.tsv"
  TEST_GENES_PATH: "../data/test_data/holdout_genes.xlsx"
  ADULT_ACTIONABLE_GENES_PATH: "../data/test_data/ACI-overview-adult.tsv"
  PREDIATRIC_ACTIONABLE_GENES_PATH: "../data/test_data/ACI-overview-pediatric.tsv"
  BINDING_AFFINITY_PATH: "../data/bindingdb/BindingDB_All_202312.tsv"
  TISSUE_EXPRESSION_PATH: "../data/hpa/normal_tissue.tsv"
  TISSUE_EXPRESSION_DESC_PATH: "../data/hpa/rna_single_cell_cluster_description.tsv"

varipred:
  num_batches: 1000

hyperparameters:
  mlp:
    optimizer: Adam
    lr_start: 1e-3
    lr_end: 1e-3
    epochs: 100
    width: 256
    batch_size: 64
    num_layers: 4
    threshold: 0.6
    dropout: 0.0
    num_workers: 0
    weight_decay: 0.0
    wandb: False
  varformer:
    usage: True
    optimizer: Adam
    lr_start: 1e-3
    max_seq_len: 4096  # standard 4096
    d_model: 768 # standard 768
    reduction: None # choose from "padding", "pooling" or None
    batch_size: 64 # standard 64
    nhead: 1 # tunable hyperparam
    num_encoder_layers: 1 # tunable hyperparam
    shard_size: 512
    num_workers: 0
  plddt_autoencoder:
    usage: None
  puupl:
    optimizer: Adam
    lr_start: 1e-3
    lr_end: 1e-3
    epochs: 100
    width: 64
    batch_size: 128
    depth: 16
    threshold: 0.5
    dropout: 0.5
    num_workers: 0
    weight_decay: 0.01
