paths:
  MIVA_PATH: "../data/elgh/all_functional.gatk_PASS.FS_30.DP_0.GQ_20.AB_0.01.functional.missingness_lt_0.genotype_counts.present_in_ELGH.n_transcripts_corrected.txt"
  GENOME_PATH: "../data/hg38.fasta"
  VP_INFERENCE_PATH: "../models/VariPred/VariPred/predict.sh"
  VP_TRAINING_PATH: "../models/VariPred/VariPred/train_VariPred.sh"
  VP_OUTPUT_PATH: "../data/VariPred/finetuned_output_1/"
  AF_PATH: "../data/alphafold/alphafold_cifs/"

varipred:
  num_batches: 1000

mlp:
  lr: 1e-3
  epochs: 10
  width_1: 6
  width_2: 6
  batch_size: 32