paths:
  ALL_GH: "../data/elgh/gh_parts/processed_gh_data/filtered_csqs.pkl"
  MIVA_PATH: "../data/elgh/all_functional.gatk_PASS.FS_30.DP_0.GQ_20.AB_0.01.functional.missingness_lt_0.genotype_counts.present_in_ELGH.n_transcripts_corrected.txt"
  GENOME_PATH: "../data/hg38.fasta"
  VP_INFERENCE_PATH: "../models/VariPred/VariPred/predict.sh"
  VP_TRAINING_PATH: "../models/VariPred/VariPred/train_VariPred.sh"
  VP_OUTPUT_PATH: "../data/VariPred/finetuned_output_1/"
  AF_PATH: "../data/alphafold/alphafold_cifs/"
  # AM_PATH: "../data/alphamissense/AlphaMissense_hg38.tsv"
  AM_PATH: "/data/scratch/bty174/genomic_drug_targeting/data/alphamissense/AlphaMissense_hg38.tsv"  # for cluster
  COMMON_ESSENTIALS_PATH: "../data/depmap/CRISPRInferredCommonEssentials.csv" # 23Q2 release
  GENE_DRUG_EVIDENCE_PATH: "../data/pharmgkb/clinicalAnnotations/clinical_annotations.tsv"
  PROTEIN_ATLAS_FEATURES: "../data/hpa/proteinatlas.tsv"
  TEST_GENES_PATH: "../data/test_data/holdout_genes.xlsx"
  ADULT_ACTIONABLE_GENES_PATH: "../data/test_data/ACI-overview-adult.tsv"
  PREDIATRIC_ACTIONABLE_GENES_PATH: "../data/test_data/ACI-overview-pediatric.tsv"
  BINDING_AFFINITY_PATH: "data/bindingdb/BindingDB_All_202312.tsv"
  TISSUE_EXPRESSION_PATH: "../data/hpa/normal_tissue.tsv"
  TISSUE_EXPRESSION_DESC_PATH: "../data/hpa/rna_single_cell_cluster_description.tsv"

varipred:
  num_batches: 1000

hyperparameters:
  # training and optimization
  optimizer: AdamW
  precision: "bf16"
  epochs: 100
  gradient_clip_val: 1
  batch_size: 640
  lr_start: 1e-6
  lr_end: 1e-3
  T0: 200
  weight_decay: 0.01

  # architecture
  num_layers: 1   # mlp
  width: 64   # mlp
  varformer_usage: True
  max_seq_len: 1024 # transformer
  num_encoder_layers: 2   # transformeer
  d_model: 768  # transformer
  nhead: 1  # transformer
  reduction: None # choose from "padding", "pooling" or None
  dropout: 0.3
  threshold: 0.2

  # misc
  wandb: True
  num_workers: 0
  seed: 42
